# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  apply:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # install terraform
      - uses: hashicorp/setup-terraform@v1
      # install aws with configure on env vars
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TERRAFORM_AWS_SECRET }}
          aws-region: us-east-1
      
      # Runs a set of commands using the runners shell
      - name: Assume Role
        run: |
          sudo apt-get install jq
          temp_role=$(aws sts assume-role \
                    --role-arn "arn:aws:iam::073157105290:role/dev_admin" \
                    --role-session-name "AWSCLI-Session")
          export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq -r .Credentials.AccessKeyId)
          export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq -r .Credentials.SecretAccessKey)
          export AWS_SESSION_TOKEN=$(echo $temp_role | jq -r .Credentials.SessionToken)
          aws sts get-caller-identity
