# workflow only runs on pull request
name: Terraform plan
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [master]
    paths:
      - "dev/**"
      - "prod/**"
      - "staging/**"
      - "root/**"
      - "modules/**"
      - "assets/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # terraform plan job
  plan:
    runs-on: ubuntu-latest
    steps:
      # Checks-out repo
      - uses: actions/checkout@v2

      # install terraform
      - uses: hashicorp/setup-terraform@v1.3.2

      # get path changed
      - uses: dorny/paths-filter@v2
        id: edited_files
        with:
          filters: |
            dev:  
              - 'dev/**'
            staging:
              - 'staging/**'
            prod:
              - 'prod/**'
            root:
              - 'root/**'
            common:
              - 'modules/**'
              - 'assets/**'

      # install aws with configure on env vars
      - name: Configure AWS Dev
        if: steps.edited_files.outputs.dev == 'true' || steps.edited_files.outputs.common == 'true'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TERRAFORM_AWS_SECRET }}
          role-to-assume: arn:aws:iam::824611589741:role/dev_admin
          role-session-name: terraform-dev
          aws-region: us-east-1
          role-duration-seconds: 1200

      # check if dev edited
      - name: Terraform plan dev us-east-1
        if: steps.edited_files.outputs.dev == 'true' || steps.edited_files.outputs.common == 'true'
        run: |
          cd dev/us-east-1
          terraform init
          terraform plan

      - name: Terraform plan dev global
        if: steps.edited_files.outputs.dev == 'true' || steps.edited_files.outputs.common == 'true'
        run: |
          cd dev/global
          terraform init
          terraform plan

      # install aws with configure on env vars
      - name: Configure AWS Staging
        if: steps.edited_files.outputs.staging == 'true' || steps.edited_files.outputs.common == 'true'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TERRAFORM_AWS_SECRET }}
          role-to-assume: arn:aws:iam::096377267832:role/stage_admin
          role-session-name: terraform-staging
          aws-region: us-east-1
          role-duration-seconds: 1200

      # check if staging edited
      - name: Terraform plan staging us-east-1
        if: steps.edited_files.outputs.staging == 'true' || steps.edited_files.outputs.common == 'true'
        run: |
          cd staging/us-east-1
          terraform init 
          terraform plan

      - name: Terraform plan staging global
        if: steps.edited_files.outputs.staging == 'true' || steps.edited_files.outputs.common == 'true'
        run: |
          cd staging/global
          terraform init 
          terraform plan

      # install aws with configure on env vars
      - name: Configure AWS Prod
        if: steps.edited_files.outputs.prod == 'true' || steps.edited_files.outputs.common == 'true'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TERRAFORM_AWS_SECRET }}
          role-to-assume: arn:aws:iam::980636768267:role/prod_admin
          role-session-name: terraform-prod
          aws-region: us-east-1
          role-duration-seconds: 1200

      # check if prod edited
      - name: Terraform plan prod us-east-1
        if: steps.edited_files.outputs.prod == 'true' || steps.edited_files.outputs.common == 'true'
        run: |
          cd prod/us-east-1
          terraform init
          terraform plan

      - name: Terraform plan prod global
        if: steps.edited_files.outputs.prod == 'true' || steps.edited_files.outputs.common == 'true'
        run: |
          cd prod/global
          terraform init
          terraform plan

      # install aws with configure on env vars
      - name: Configure AWS Root
        if: steps.edited_files.outputs.root == 'true' || steps.edited_files.outputs.common == 'true'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TERRAFORM_AWS_SECRET }}
          role-session-name: terraform-root
          aws-region: us-east-1
          role-duration-seconds: 1200

      # check if root edited
      - name: Terraform plan root
        if: steps.edited_files.outputs.root == 'true' || steps.edited_files.outputs.common == 'true'
        run: |
          cd root/global
          terraform init
          terraform plan
